import { test, expect } from '@playwright/test'
import jsQR from 'jsqr'
test('anonymous question, answer, search and bookmark flow', async ({ page }) => {
  const runtimeErrors: string[] = []
  page.on('pageerror', error => runtimeErrors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await expect(page.getByText('Apa hal kecil yang belakangan ini bikin kamu merasa bahagia?', { exact: true }).first()).toBeVisible()
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Buat pertanyaan', exact: true }).click()
  await page.getByLabel('Pertanyaanmu').fill('Bagaimana cara menemukan hobi baru yang menyenangkan?')
  await page.getByLabel('Sedikit konteks').fill('Aku ingin mencoba kegiatan baru di akhir pekan.')
  await page.getByRole('button', { name: 'Kirim pertanyaan' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Bagaimana cara menemukan hobi baru yang menyenangkan?')
  await expect(page).toHaveURL(/\/[A-Z]{5}$/)
  const shortCode = new URL(page.url()).pathname.slice(1)
  await expect(page.getByTestId('question-code')).toHaveText(shortCode)
  await expect(page.getByLabel('Tautan pendek pertanyaan')).toHaveValue(page.url())
  const qr = page.getByRole('img', { name: `QR tautan pertanyaan ${shortCode}` })
  await expect(qr).toBeVisible()
  const pixels = await qr.evaluate(async (element: HTMLImageElement) => {
    await element.decode()
    const canvas = document.createElement('canvas'); canvas.width = element.naturalWidth; canvas.height = element.naturalHeight
    const context = canvas.getContext('2d')!; context.drawImage(element, 0, 0)
    return { data: Array.from(context.getImageData(0, 0, canvas.width, canvas.height).data), width: canvas.width, height: canvas.height }
  })
  expect(jsQR(new Uint8ClampedArray(pixels.data), pixels.width, pixels.height)?.data).toBe(page.url())
  await page.screenshot({ path: 'test-results/question-share.png', fullPage: true })
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Unduh QR' }).click()
  expect((await downloadPromise).suggestedFilename()).toBe(`dheepask-${shortCode}.png`)
  await page.getByLabel('Jawaban anonim').fill('Coba kelas melukis atau jalan santai di taman.')
  await page.getByRole('button', { name: 'Kirim jawaban' }).click()
  await expect(page.getByText('Coba kelas melukis atau jalan santai di taman.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Coba kelas melukis atau jalan santai di taman.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Simpan pertanyaan' }).click()
  await page.getByRole('button', { name: 'Tersimpan', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pertanyaan tersimpan' })).toBeVisible()
  await expect(page.locator('.question-card')).toHaveCount(1)
  await page.getByLabel('Cari pertanyaan').fill('kata-tidak-ada')
  await expect(page.locator('.question-card')).toHaveCount(0)
  expect(runtimeErrors).toEqual([])
})
test('manual code entry, case-insensitive codes and legacy links', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Kode pertanyaan 5 huruf').fill('acfgh')
  await page.getByRole('button', { name: 'Buka', exact: true }).click()
  await expect(page).toHaveURL(/\/ACFGH$/)
  await expect(page.getByRole('heading', { level: 1 })).toContainText('mengulang satu hari')
  await page.goto('/acfgh')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('mengulang satu hari')
  await page.goto('/questions/55555555-5555-4555-8555-555555555555')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('mengulang satu hari')
  await expect(page.getByLabel('Tautan pendek pertanyaan')).toHaveValue('http://127.0.0.1:3107/ACFGH')
  await page.goto('/12345')
  await expect(page.getByRole('heading', { name: 'Pertanyaan tidak ditemukan.' })).toBeVisible()
})
test('mobile layout and topic navigation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.question-card').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Buka navigasi' }).click()
  await page.locator('.topic-nav').filter({ hasText: 'Karier' }).click()
  await expect(page.locator('.question-card')).toHaveCount(1)
  await expect(page.locator('.question-card')).toContainText('passion')
  await page.goto('/ktmxz')
  await expect(page.getByRole('img', { name: 'QR tautan pertanyaan KTMXZ' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/question-share-mobile.png', fullPage: true })
})
test('existing demo questions, answers and bookmarks survive code migration', async ({ page }) => {
  const oldId = 'abcdefab-1234-4234-8234-123456789abc'
  await page.addInitScript((id) => {
    if (localStorage.getItem('dheepask-demo-v1')) return
    localStorage.setItem('dheepask-demo-v1', JSON.stringify({ questions: [{ id, title: 'Pertanyaan lama yang tetap tersimpan', body: 'Konteks lama', category: 'Random', created_at: new Date().toISOString(), answer_count: 1 }], answers: [{ id: 'old-answer', question_id: id, body: 'Jawaban lama tetap utuh', created_at: new Date().toISOString() }] }))
    localStorage.setItem('dheepask-bookmarks', JSON.stringify([id]))
  }, oldId)
  await page.goto(`/questions/${oldId}`)
  await expect(page.getByText('Jawaban lama tetap utuh')).toBeVisible()
  await expect(page.getByTestId('question-code')).toHaveText(/^[A-Z]{5}$/)
  const code = await page.getByTestId('question-code').innerText()
  await expect(page.getByRole('button', { name: 'Simpan pertanyaan' })).toHaveAttribute('aria-pressed', 'true')
  await page.goto(`/${code.toLowerCase()}`)
  await expect(page.getByText('Jawaban lama tetap utuh')).toBeVisible()
  await expect(page.getByTestId('question-code')).toHaveText(code)
})
