import { test, expect } from '@playwright/test'
import jsQR from 'jsqr'

test('realtime demo updates questions and nested replies across tabs without losing drafts', async ({ page, context }) => {
  await page.goto('/')
  await expect(page.locator('.question-card').first()).toBeVisible()
  const writer = await context.newPage()
  await writer.goto('/')
  await expect(page.getByTestId('site-hits')).toHaveText('2')
  await writer.getByRole('button', { name: 'Kirim reaksi ❤️ Suka', exact: true }).click()
  await expect(page.getByTestId('reaction-count-heart')).toHaveText('1')
  await writer.getByRole('button', { name: 'Buat pertanyaan', exact: true }).click()
  await writer.getByLabel('Pertanyaanmu').fill('Pertanyaan baru langsung muncul antar tab?')
  await writer.getByRole('button', { name: 'Kirim pertanyaan' }).click()
  await expect(writer).toHaveURL(/\/[A-Z]{5}$/)
  await expect(page.getByRole('heading', { name: 'Pertanyaan baru langsung muncul antar tab?' })).toBeVisible()
  await page.goto('/KTMXZ'); await writer.goto('/KTMXZ')
  await page.getByLabel('Jawaban anonim').fill('Draft jawaban belum dikirim')
  const root = page.locator('[data-answer-id="demo-a1"]')
  await root.getByRole('button', { name: /^Balas anon-/ }).click()
  await root.getByRole('textbox').fill('Draft balasan belum dikirim')
  await writer.getByLabel('Jawaban anonim').fill('Jawaban realtime dari tab lainnya')
  await writer.getByRole('button', { name: 'Kirim jawaban' }).click()
  await expect(page.getByText('Jawaban realtime dari tab lainnya', { exact: true })).toBeVisible()
  const otherRoot = writer.locator('[data-answer-id="demo-a1"]')
  await otherRoot.getByRole('button', { name: /^Balas anon-/ }).click()
  await otherRoot.getByRole('textbox').fill('Komentar thread realtime dari tab lainnya')
  await otherRoot.getByRole('button', { name: 'Kirim balasan', exact: true }).click()
  await expect(root.getByText('Komentar thread realtime dari tab lainnya', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Jawaban anonim')).toHaveValue('Draft jawaban belum dikirim')
  await expect(root.getByRole('textbox')).toHaveValue('Draft balasan belum dikirim')
  await expect(page.getByText('4 jawaban', { exact: true })).toBeVisible()
  await writer.evaluate(() => {
    const saved = JSON.parse(localStorage.getItem('dheepask-demo-v1')!)
    saved.questions.find((q: { short_code: string }) => q.short_code === 'KTMXZ').title = 'Judul diedit otomatis dari tab lain'
    saved.answers = saved.answers.filter((a: { body: string }) => a.body !== 'Jawaban realtime dari tab lainnya')
    localStorage.setItem('dheepask-demo-v1', JSON.stringify(saved))
  })
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Judul diedit otomatis dari tab lain')
  await expect(page.getByText('Jawaban realtime dari tab lainnya', { exact: true })).toHaveCount(0)
  await expect(root.getByRole('textbox')).toHaveValue('Draft balasan belum dikirim')
  await writer.close()
})

test('realtime demo private room questions and answers stay out of the public feed', async ({ page, context }) => {
  await page.goto('/rooms/new')
  await page.getByLabel('Nama ruang').fill('Room realtime antar tab')
  await page.getByLabel('Konteks ruang').fill('Konteks diskusi realtime.')
  await page.getByLabel('Kode tautan').fill('realtime-demo')
  await page.getByRole('button', { name: 'Buat ruang', exact: true }).click()
  await expect(page).toHaveURL(/\/r\/realtime-demo$/)
  const writer = await context.newPage(); await writer.goto('/r/realtime-demo')
  await writer.getByRole('button', { name: 'Tanya di ruang ini' }).click()
  await writer.getByLabel('Pertanyaanmu').fill('Pertanyaan privat muncul secara realtime?')
  await writer.getByRole('button', { name: 'Kirim pertanyaan' }).click()
  await expect(writer).toHaveURL(/\/r\/realtime-demo\/[A-Z]{5}$/)
  await expect(page.getByRole('heading', { name: 'Pertanyaan privat muncul secara realtime?' })).toBeVisible()
  await page.goto(writer.url())
  await writer.getByLabel('Jawaban anonim').fill('Jawaban privat realtime')
  await writer.getByRole('button', { name: 'Kirim jawaban' }).click()
  await expect(page.getByText('Jawaban privat realtime', { exact: true })).toBeVisible()
  await page.goto('/')
  await expect(page.locator('.question-card').first()).toBeVisible()
  await expect(page.getByText('Pertanyaan privat muncul secara realtime?', { exact: true })).toHaveCount(0)
  await writer.close()
})
test('anonymous question, answer, search and bookmark flow', async ({ page }) => {
  const runtimeErrors: string[] = []
  page.on('pageerror', error => runtimeErrors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await expect(page.getByText('Apa hal kecil yang belakangan ini bikin kamu merasa bahagia?', { exact: true }).first()).toBeVisible()
  await page.mouse.move(1100, 350)
  const scrollShift = () => page.locator('.immersive-atmosphere').evaluate(element => parseFloat((element as HTMLElement).style.getPropertyValue('--parallax-y')))
  expect(await scrollShift()).toBe(0)
  await page.evaluate(() => window.scrollTo({ top: 250, behavior: 'instant' }))
  await expect.poll(scrollShift).toBeGreaterThan(100)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect.poll(scrollShift).toBe(0)
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await expect.poll(scrollShift).toBeGreaterThan(100)
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await expect.poll(scrollShift).toBeLessThan(.2)
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  await page.screenshot({ path: 'test-results/home-viewport.png' })
  await page.getByRole('button', { name: 'Buat pertanyaan', exact: true }).click()
  await page.getByLabel('Pertanyaanmu').fill('Bagaimana cara menemukan hobi baru yang menyenangkan?')
  await page.getByLabel('Sedikit konteks').fill('Aku ingin mencoba kegiatan baru di akhir pekan.')
  await page.screenshot({ path: 'test-results/ask-modal.png' })
  await page.getByRole('button', { name: 'Kirim pertanyaan' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Bagaimana cara menemukan hobi baru yang menyenangkan?')
  await expect(page).toHaveURL(/\/[A-Z]{5}$/)
  const shortCode = new URL(page.url()).pathname.slice(1)
  await expect(page.getByTestId('question-code')).toHaveText(shortCode)
  await expect(page.getByLabel('Tautan pendek pertanyaan')).toHaveValue(page.url())
  const qr = page.getByRole('img', { name: `QR tautan pertanyaan ${shortCode}` })
  await expect(qr).toBeVisible()
  const pixels = await qr.evaluate(async (element: HTMLImageElement) => {
    await element.decode()
    const canvas = document.createElement('canvas'); canvas.width = element.naturalWidth; canvas.height = element.naturalHeight
    const context = canvas.getContext('2d')!; context.drawImage(element, 0, 0)
    return { data: Array.from(context.getImageData(0, 0, canvas.width, canvas.height).data), width: canvas.width, height: canvas.height }
  })
  expect(jsQR(new Uint8ClampedArray(pixels.data), pixels.width, pixels.height)?.data).toBe(page.url())
  await page.screenshot({ path: 'test-results/question-share.png', fullPage: true })
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Unduh QR' }).click()
  expect((await downloadPromise).suggestedFilename()).toBe(`dheepask-${shortCode}.png`)
  await page.getByLabel('Jawaban anonim').fill('Coba kelas melukis atau jalan santai di taman.')
  await page.getByRole('button', { name: 'Kirim jawaban' }).click()
  await expect(page.getByText('Coba kelas melukis atau jalan santai di taman.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Coba kelas melukis atau jalan santai di taman.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Simpan pertanyaan' }).click()
  await page.getByRole('button', { name: 'Tersimpan', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pertanyaan tersimpan' })).toBeVisible()
  await expect(page.locator('.question-card')).toHaveCount(1)
  await page.getByLabel('Cari pertanyaan').fill('kata-tidak-ada')
  await expect(page.locator('.question-card')).toHaveCount(0)
  expect(runtimeErrors).toEqual([])
})
test('nested replies stay in their thread after refresh on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/KTMXZ')
  const root = page.locator('[data-answer-id="demo-a1"]')
  await root.getByRole('button', { name: /^Balas anon-/ }).click()
  await root.getByRole('textbox').fill('Ada rekomendasi kopi untuk pagi hari?')
  await root.getByRole('button', { name: 'Batal', exact: true }).click()
  await expect(root.getByRole('textbox')).toHaveCount(0)
  await root.getByRole('button', { name: /^Balas anon-/ }).click()
  await root.getByRole('textbox').fill('Ada rekomendasi kopi untuk pagi hari?')
  await root.getByRole('button', { name: 'Kirim balasan', exact: true }).click()
  const child = root.getByRole('article').first()
  await expect(child).toContainText('Ada rekomendasi kopi untuk pagi hari?')
  await child.getByRole('button', { name: /^Balas anon-/ }).click()
  await child.getByRole('textbox').fill('Aku biasanya pilih kopi susu yang ringan.')
  await child.getByRole('button', { name: 'Kirim balasan', exact: true }).click()
  await expect(child.getByRole('article')).toContainText('Aku biasanya pilih kopi susu yang ringan.')
  await expect(page.getByText('4 jawaban', { exact: true })).toBeVisible()
  await page.reload()
  await expect(root.getByRole('article').first().getByRole('article')).toContainText('Aku biasanya pilih kopi susu yang ringan.')
  await expect(page.locator('[data-answer-id="demo-a2"]').getByRole('article')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('private room context, stable aliases and public feed isolation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('link', { name: 'Buat ruang private', exact: true }).click()
  await page.getByLabel('Nama ruang').fill('Tanya apa aja tentang gw!')
  await page.getByLabel('Konteks ruang').fill('Boleh tanya soal hobi dan keseharianku.')
  await page.getByRole('button', { name: 'Buat ruang', exact: true }).click()
  await expect(page).toHaveURL(/\/r\/[A-Z]{7}$/)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Tanya apa aja tentang gw!')
  const roomUrl = page.url()
  const alias = await page.getByTestId('my-alias').innerText()
  expect(alias).toMatch(/^anon-[a-f0-9]{8}$/)
  await expect(page.getByLabel('Tautan private')).toHaveValue(roomUrl)
  await page.getByRole('button', { name: 'Tanya di ruang ini' }).click()
  await page.getByLabel('Pertanyaanmu').fill('Apa hobi kamu akhir-akhir ini?')
  await page.getByRole('button', { name: 'Kirim pertanyaan' }).click()
  await expect(page).toHaveURL(/\/r\/[A-Z]{7}\/[A-Z]{5}$/)
  const questionUrl = page.url(); const code = questionUrl.split('/').at(-1)
  await expect(page.getByText('Boleh tanya soal hobi dan keseharianku.', { exact: true })).toBeVisible()
  await expect(page.getByText(alias, { exact: true })).toBeVisible()
  await page.getByLabel('Jawaban anonim').fill('Aku sekarang suka melukis.')
  await page.getByRole('button', { name: 'Kirim jawaban', exact: true }).click()
  const answer = page.locator('[data-answer-id]').first()
  await expect(answer.getByRole('paragraph').filter({ hasText: alias })).toBeVisible()
  await answer.getByRole('button', { name: `Balas ${alias}`, exact: true }).click()
  await answer.getByRole('textbox').fill('Biasanya melukis pemandangan.')
  await answer.getByRole('button', { name: 'Kirim balasan', exact: true }).click()
  await page.reload()
  await expect(answer.getByRole('article').getByRole('paragraph').filter({ hasText: alias })).toBeVisible()
  await page.getByRole('link', { name: 'Kembali ke ruang' }).click()
  await expect(page.getByTestId('my-alias')).toHaveText(alias)
  const oldToken = await page.evaluate(() => JSON.parse(localStorage.getItem('dheepask-demo-v1')!).rooms[0].token)
  await page.goto(`/rooms/${oldToken}`)
  await expect(page).toHaveURL(roomUrl)
  await expect(page.getByTestId('my-alias')).toHaveText(alias)
  await page.goto(`/rooms/${oldToken}/questions/${code}`)
  await expect(page).toHaveURL(questionUrl)
  await page.goto(roomUrl.toLowerCase())
  await expect(page).toHaveURL(roomUrl)
  await expect(page.getByRole('heading', { name: 'Apa hobi kamu akhir-akhir ini?' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/private-room-mobile.png', fullPage: true })
  await page.goto('/')
  await expect(page.getByText('Apa hobi kamu akhir-akhir ini?', { exact: true })).toHaveCount(0)
  await page.goto(`/${code}`)
  await expect(page.getByRole('heading', { name: 'Pertanyaan tidak ditemukan.' })).toBeVisible()
  await page.goto('/rooms/00000000-0000-4000-8000-000000000000')
  await expect(page.getByRole('heading', { name: 'Ruang tidak ditemukan.' })).toBeVisible()
})

test('custom room links reject duplicates and preserve old demo rooms', async ({ page }) => {
  await page.goto('/rooms/new')
  await page.getByLabel('Nama ruang').fill('Tanya apa aja tentang aku!')
  await page.getByLabel('Konteks ruang').fill('Sesi tanya jawab soal hobi.')
  await page.getByLabel('Kode tautan').fill('tanya-gw')
  await page.getByRole('button', { name: 'Buat ruang', exact: true }).click()
  await expect(page).toHaveURL(/\/r\/tanya-gw$/)
  await expect(page.getByLabel('Tautan private')).toHaveValue('http://127.0.0.1:3107/r/tanya-gw')
  await page.goto('/r/TANYA-GW')
  await expect(page).toHaveURL(/\/r\/tanya-gw$/)
  await page.goto('/rooms/new')
  await page.getByLabel('Nama ruang').fill('Room duplikat baru')
  await page.getByLabel('Konteks ruang').fill('Konteks room duplikat.')
  await page.getByLabel('Kode tautan').fill('TANYA-GW')
  await page.getByRole('button', { name: 'Buat ruang', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Kode ruang sudah dipakai. Pilih kode lain.')
  await expect(page.getByLabel('Nama ruang')).toHaveValue('Room duplikat baru')
  await page.getByLabel('Kode tautan').fill('room-baru')
  await page.getByRole('button', { name: 'Buat ruang', exact: true }).click()
  await expect(page).toHaveURL(/\/r\/room-baru$/)
})

test('existing demo UUID room gains a short link without losing its data', async ({ page }) => {
  const token = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
  const id = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'
  await page.addInitScript(({ token, id }) => {
    if (localStorage.getItem('dheepask-demo-v1')) return
    localStorage.setItem('dheepask-demo-v1', JSON.stringify({ questions: [{ id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc', room_id: id, short_code: 'ABCDE', title: 'Pertanyaan lama di ruang private', body: '', category: 'Random', created_at: new Date().toISOString(), answer_count: 0, anon_name: 'anon-12345678' }], answers: [], rooms: [{ id, token, title: 'Ruang lama', context: 'Konteks tetap utuh', created_at: new Date().toISOString(), my_alias: 'anon-12345678', is_owner: true }], aliases: { [id]: 'anon-12345678' } }))
  }, { token, id })
  await page.goto(`/rooms/${token}`)
  await expect(page).toHaveURL(/\/r\/[A-Z]{7}$/)
  const url = page.url()
  await expect(page.getByTestId('my-alias')).toHaveText('anon-12345678')
  await expect(page.getByText('Konteks tetap utuh')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Pertanyaan lama di ruang private' })).toBeVisible()
  await page.reload()
  await expect(page).toHaveURL(url)
  await expect(page.getByTestId('my-alias')).toHaveText('anon-12345678')
})

test('hero counts visits and accepts repeated animated reactions', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByTestId('site-hits')).toHaveText('1')
  const heart = page.getByRole('button', { name: 'Kirim reaksi ❤️ Suka', exact: true })
  const fire = page.getByRole('button', { name: 'Kirim reaksi 🔥 Keren', exact: true })
  await expect(heart).toBeEnabled()
  await heart.evaluate((button: HTMLButtonElement) => { for (let i = 0; i < 75; i++) button.click() })
  await fire.click()
  await expect(page.getByTestId('reaction-count-heart')).toHaveText('75')
  await expect(page.getByTestId('reaction-count-fire')).toHaveText('1')
  await expect(page.locator('.reaction-burst').first()).toBeVisible()
  for (const key of ['heart', 'laugh', 'fire', 'clap', 'wow', 'love']) {
    await expect.poll(() => page.locator(`[data-reaction="${key}"]`).evaluate((el: HTMLImageElement, reactionKey) => el.complete && el.naturalWidth > 0 && el.currentSrc.endsWith(`/emoji/noto/${reactionKey}.webp`), key)).toBe(true)
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/hero-reactions-mobile.png' })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect.poll(() => page.locator('[data-reaction="heart"]').evaluate((el: HTMLImageElement) => el.currentSrc.endsWith('/emoji/noto/heart.png'))).toBe(true)
  expect(await page.locator('[data-reaction="heart"]').evaluate(el => getComputedStyle(el).animationName)).toBe('none')
  await heart.click()
  await expect(page.getByTestId('reaction-count-heart')).toHaveText('76')
  await expect(page.locator('.reaction-burst').first()).toBeHidden()
  await page.reload()
  await expect(page.getByTestId('site-hits')).toHaveText('2')
  await expect(page.getByTestId('reaction-count-heart')).toHaveText('76')
  await expect(page.getByTestId('reaction-count-fire')).toHaveText('1')
  // Filtering the feed updates the URL without counting a new page visit.
  await page.getByRole('button', { name: 'Karier', exact: true }).click()
  await expect(page.getByTestId('site-hits')).toHaveText('2')
})

test('holding a reaction repeats until released, cancelled or unfocused', async ({ page }) => {
  await page.goto('/')
  const heart = page.getByRole('button', { name: 'Kirim reaksi ❤️ Suka', exact: true })
  const fire = page.getByRole('button', { name: 'Kirim reaksi 🔥 Keren', exact: true })
  const heartCount = page.getByTestId('reaction-count-heart')
  const fireCount = page.getByTestId('reaction-count-fire')
  const count = async () => Number((await heartCount.innerText()).replaceAll('.', ''))
  await expect(heart).toBeEnabled()
  await heart.click()
  await expect(heartCount).toHaveText('1')
  await heart.hover()
  await page.mouse.down()
  await expect.poll(count).toBeGreaterThan(4)
  await page.mouse.up()
  const released = await count()
  await page.waitForTimeout(250)
  expect(await count()).toBe(released)
  await heart.click()
  await expect(heartCount).toHaveText(String(released + 1))
  // Switching focus between reaction buttons must not cancel the new hold.
  await fire.hover()
  await page.mouse.down()
  await expect.poll(async () => Number(await fireCount.innerText())).toBeGreaterThan(3)
  await page.mouse.move(10, 10)
  await page.mouse.up()
  const fireReleased = await fireCount.innerText()
  await page.waitForTimeout(250)
  await expect(fireCount).toHaveText(fireReleased)
  await heart.focus()
  await page.keyboard.down('Space')
  const keyboardStart = await count()
  await expect.poll(count).toBeGreaterThan(keyboardStart + 2)
  await page.keyboard.up('Space')
  const keyboardReleased = await count()
  await page.waitForTimeout(250)
  expect(await count()).toBe(keyboardReleased)
  await page.keyboard.press('Enter')
  await expect(heartCount).toHaveText(String(keyboardReleased + 1))
  await heart.hover()
  await page.mouse.down()
  await expect(heart).toHaveClass(/is-holding/)
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await page.mouse.up()
  const blurred = await count()
  await page.waitForTimeout(400)
  expect(await count()).toBe(blurred)
  // Touch cancellation, such as a browser taking over a scrolling gesture.
  await heart.dispatchEvent('pointerdown', { pointerId: 42, pointerType: 'touch', isPrimary: true, button: 0 })
  await expect(heart).toHaveClass(/is-holding/)
  await expect.poll(count).toBeGreaterThan(blurred + 2)
  await heart.dispatchEvent('pointercancel', { pointerId: 42, pointerType: 'touch' })
  const cancelled = await count()
  await page.waitForTimeout(250)
  expect(await count()).toBe(cancelled)
  await expect(heart).not.toHaveClass(/is-holding/)
  await page.reload()
  await expect(heartCount).toHaveText(String(cancelled))
})

test('touchscreen hold repeats and a short tap counts exactly once', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true })
  try {
    const page = await context.newPage()
    await page.goto('http://127.0.0.1:3107/')
    const heart = page.getByRole('button', { name: 'Kirim reaksi ❤️ Suka', exact: true })
    const count = page.getByTestId('reaction-count-heart')
    await expect(heart).toBeEnabled()
    await heart.tap()
    await expect(count).toHaveText('1')
    const bounds = (await heart.boundingBox())!
    const touch = await context.newCDPSession(page)
    await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height / 2 }] })
    await expect.poll(async () => Number(await count.innerText())).toBeGreaterThan(5)
    await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await expect(heart).not.toHaveClass(/is-holding/)
    const released = await count.innerText()
    await page.waitForTimeout(300)
    await expect(count).toHaveText(released)
  } finally { await context.close() }
})

test('manual code entry, case-insensitive codes and legacy links', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Kode pertanyaan 5 huruf').fill('acfgh')
  await page.getByRole('button', { name: 'Buka', exact: true }).click()
  await expect(page).toHaveURL(/\/ACFGH$/)
  await expect(page.getByRole('heading', { level: 1 })).toContainText('mengulang satu hari')
  await page.goto('/acfgh')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('mengulang satu hari')
  await page.goto('/questions/55555555-5555-4555-8555-555555555555')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('mengulang satu hari')
  await expect(page.getByLabel('Tautan pendek pertanyaan')).toHaveValue('http://127.0.0.1:3107/ACFGH')
  await page.goto('/12345')
  await expect(page.getByRole('heading', { name: 'Pertanyaan tidak ditemukan.' })).toBeVisible()
})
test('mobile layout and topic navigation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.question-card').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  await page.screenshot({ path: 'test-results/mobile-viewport.png' })
  const glow = page.locator('.hero-glow')
  expect(await glow.evaluate(element => getComputedStyle(element).animationName)).toBe('glow-drift')
  const initialTransform = await glow.evaluate(element => getComputedStyle(element).transform)
  await page.waitForTimeout(250)
  expect(await glow.evaluate(element => getComputedStyle(element).transform)).not.toBe(initialTransform)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  expect(await glow.evaluate(element => getComputedStyle(element).animationName)).toBe('none')
  expect(await page.locator('.aurora-violet').evaluate(element => getComputedStyle(element).animationName)).toBe('none')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.getByRole('button', { name: 'Buka navigasi' }).click()
  await expect(page.getByRole('button', { name: 'Buka navigasi' })).toHaveAttribute('aria-expanded', 'true')
  await page.locator('.topic-nav').filter({ hasText: 'Karier' }).click()
  await expect(page.locator('.question-card')).toHaveCount(1)
  await expect(page.locator('.question-card')).toContainText('passion')
  await page.goto('/ktmxz')
  await expect(page.getByRole('img', { name: 'QR tautan pertanyaan KTMXZ' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/question-share-mobile.png', fullPage: true })
})
test('existing demo questions, answers and bookmarks survive code migration', async ({ page }) => {
  const oldId = 'abcdefab-1234-4234-8234-123456789abc'
  await page.addInitScript((id) => {
    if (localStorage.getItem('dheepask-demo-v1')) return
    localStorage.setItem('dheepask-demo-v1', JSON.stringify({ questions: [{ id, title: 'Pertanyaan lama yang tetap tersimpan', body: 'Konteks lama', category: 'Random', created_at: new Date().toISOString(), answer_count: 1 }], answers: [{ id: 'old-answer', question_id: id, body: 'Jawaban lama tetap utuh', created_at: new Date().toISOString() }] }))
    localStorage.setItem('dheepask-bookmarks', JSON.stringify([id]))
  }, oldId)
  await page.goto(`/questions/${oldId}`)
  await expect(page.getByText('Jawaban lama tetap utuh')).toBeVisible()
  await expect(page.getByTestId('question-code')).toHaveText(/^[A-Z]{5}$/)
  const code = await page.getByTestId('question-code').innerText()
  await expect(page.getByRole('button', { name: 'Simpan pertanyaan' })).toHaveAttribute('aria-pressed', 'true')
  await page.goto(`/${code.toLowerCase()}`)
  await expect(page.getByText('Jawaban lama tetap utuh')).toBeVisible()
  await expect(page.getByTestId('question-code')).toHaveText(code)
})
