import { test, expect, type Page, type Locator } from '@playwright/test'

test('collapsed feed cards expose sharing and a working question page link', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const title = 'Apa hal kecil yang belakangan ini bikin kamu merasa bahagia?'
  const card = page.locator('.question-card').filter({ hasText: title })
  const link = card.getByRole('link', { name: 'Buka pertanyaan', exact: true })
  await expect(link).toHaveAttribute('href', '/KTMXZ')
  await expect(card.locator('.inline-replies')).toHaveCount(0)
  await card.getByRole('button', { name: 'Bagikan', exact: true }).click()
  const url = new URL('/KTMXZ', page.url()).href
  await expect(card.getByLabel('Tautan pertanyaan', { exact: true })).toHaveValue(url)
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(url)
  await expect(card.getByRole('status')).toContainText('sudah disalin')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await link.click()
  await expect(page).toHaveURL(/\/KTMXZ$/)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(title)
  await expect(page.getByTestId('question-code')).toHaveText('KTMXZ')
  await page.reload()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(title)
})

test('private feed sharing preserves the room path and offers manual copy when clipboard fails', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('Clipboard unavailable') } } })
  })
  await page.goto('/rooms/new')
  await page.getByLabel('Nama ruang').fill('Ruang bagikan pertanyaan')
  await page.getByLabel('Konteks ruang').fill('Bagikan langsung dari kartu.')
  await page.getByLabel('Kode tautan').fill('share-room')
  await page.getByRole('button', { name: 'Buat ruang', exact: true }).click()
  await page.getByRole('button', { name: 'Tanya di ruang ini' }).click()
  await page.getByLabel('Pertanyaanmu').fill('Bagaimana membagikan pertanyaan private?')
  await page.getByRole('button', { name: 'Kirim pertanyaan' }).click()
  await expect(page).toHaveURL(/\/r\/share-room\/[A-Z]{5}$/)
  const url = page.url()
  await page.getByRole('link', { name: 'Kembali ke ruang' }).click()
  const card = page.locator('.question-card').filter({ hasText: 'Bagaimana membagikan pertanyaan private?' })
  await card.getByRole('button', { name: 'Bagikan', exact: true }).click()
  await expect(card.getByLabel('Tautan pertanyaan', { exact: true })).toHaveValue(url)
  await expect(card.getByRole('status')).toContainText('salin tautan')
  await card.getByRole('link', { name: 'Buka pertanyaan', exact: true }).click()
  await expect(page).toHaveURL(url)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Bagaimana membagikan pertanyaan private?')
})

async function chooseEmoji(page: Page, answer: Locator, query: string, emoji: string) {
  await answer.getByRole('button', { name: 'Tambah reaction', exact: true }).click()
  const picker = page.getByRole('dialog', { name: 'Pilih reaction emoji' })
  await picker.getByPlaceholder('Cari emoji', { exact: true }).fill(query)
  await picker.getByRole('button', { name: emoji, exact: true }).click()
  await expect(picker).toHaveCount(0)
}

test('feed expands in place, preserves drafts and supports nested replies and reaction changes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const card = page.locator('.question-card').filter({ hasText: 'Apa hal kecil yang belakangan ini bikin kamu merasa bahagia?' })
  const toggle = card.getByRole('button', { name: /jawaban.*Lihat & balas/ })
  await toggle.click()
  await expect(page).toHaveURL(/\/$/)
  const root = card.locator('[data-answer-id="demo-a1"]')
  await expect(root).toBeVisible()
  await expect(root.getByRole('button', { name: /^Reaksi / })).toHaveCount(0)
  const heart = root.getByRole('button', { name: 'Reaksi ❤️, 1', exact: true })
  const cat = root.getByRole('button', { name: 'Reaksi 🐈, 1', exact: true })
  await chooseEmoji(page, root, 'heart', '❤️')
  await expect(heart).toHaveAttribute('aria-pressed','true')
  await chooseEmoji(page, root, 'cat', '🐈')
  await expect(heart).toBeVisible()
  await expect(cat).toHaveAttribute('aria-pressed','true')
  await cat.click()
  await expect(cat).toHaveCount(0)
  await card.getByLabel('Jawaban anonim', { exact: true }).fill('Draft yang tetap ada saat ditutup')
  await card.getByRole('button', { name: /jawaban.*Tutup/ }).click()
  await expect(root).toBeHidden()
  await toggle.click()
  await expect(card.getByLabel('Jawaban anonim', { exact: true })).toHaveValue('Draft yang tetap ada saat ditutup')
  await root.getByRole('button', { name: /^Balas anon-/ }).click()
  await root.getByRole('textbox').fill('Balasan langsung dari feed')
  await root.getByRole('button', { name: 'Kirim balasan', exact: true }).click()
  const child = root.getByRole('article').first()
  await expect(child).toContainText('Balasan langsung dari feed')
  await chooseEmoji(page, child, 'pizza', '🍕')
  await root.getByRole('button', { name: 'Sembunyikan balasan', exact: true }).click()
  await expect(child).toBeHidden()
  await root.getByRole('button', { name: 'Lihat 1 balasan', exact: true }).click()
  await expect(child).toBeVisible()
  await page.reload()
  await toggle.click()
  await expect(heart).toContainText('1')
  await expect(heart).toHaveAttribute('aria-pressed','true')
  await root.getByRole('button', { name: 'Lihat 1 balasan', exact: true }).click()
  await expect(child.getByRole('button', { name: 'Reaksi 🍕, 1', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('private room questions can be answered and reacted to without leaving the room', async ({ page }) => {
  await page.goto('/rooms/new')
  await page.getByLabel('Nama ruang').fill('Ruang expand balasan')
  await page.getByLabel('Konteks ruang').fill('Diskusi langsung di ruang ini.')
  await page.getByLabel('Kode tautan').fill('inline-room')
  await page.getByRole('button', { name: 'Buat ruang', exact: true }).click()
  await page.getByRole('button', { name: 'Tanya di ruang ini' }).click()
  await page.getByLabel('Pertanyaanmu').fill('Bisa menjawab langsung di ruang?')
  await page.getByRole('button', { name: 'Kirim pertanyaan' }).click()
  await page.getByRole('link', { name: 'Kembali ke ruang' }).click()
  await page.getByRole('button', { name: /jawaban.*Lihat & balas/ }).click()
  await page.getByLabel('Jawaban anonim', { exact: true }).fill('Bisa, langsung dari kartu pertanyaan.')
  await page.getByRole('button', { name: 'Kirim jawaban', exact: true }).click()
  await expect(page).toHaveURL(/\/r\/inline-room$/)
  const questionReactions = page.getByRole('group', { name: 'Reaksi pertanyaan', exact: true })
  await chooseEmoji(page, questionReactions, 'cat', '🐈')
  await expect(questionReactions.getByRole('button', { name: 'Reaksi 🐈, 1', exact: true })).toBeVisible()
  await expect(page.locator('[data-answer-id]')).toContainText('Bisa, langsung dari kartu pertanyaan.')
  await chooseEmoji(page, page.locator('[data-answer-id]'), 'coffee', '☕')
  await expect(page.getByRole('button', { name: 'Reaksi ☕, 1', exact: true })).toBeVisible()
})

test('question reactions work without expanding, persist between feed and conversation, and synchronize across tabs', async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const card = page.locator('.question-card').filter({ hasText: 'Apa hal kecil yang belakangan ini bikin kamu merasa bahagia?' })
  const reactions = card.getByRole('group', { name: 'Reaksi pertanyaan', exact: true })
  await chooseEmoji(page, reactions, 'cat', '🐈')
  await chooseEmoji(page, reactions, 'coffee', '☕')
  await expect(reactions.getByRole('button', { name: 'Reaksi 🐈, 1', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(reactions.getByRole('button', { name: 'Reaksi ☕, 1', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(card.locator('[data-answer-id]')).toHaveCount(0)
  await page.goto('/KTMXZ')
  const conversationReactions = page.getByRole('group', { name: 'Reaksi pertanyaan', exact: true })
  await expect(conversationReactions.getByRole('button', { name: 'Reaksi 🐈, 1', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const answerReactions = page.locator('[data-answer-id="demo-a1"]').getByRole('group', { name: 'Reaksi jawaban', exact: true })
  await expect(answerReactions.getByRole('button', { name: /^Reaksi / })).toHaveCount(0)
  await page.getByLabel('Jawaban anonim', { exact: true }).fill('Draft saat pertanyaan mendapat reaction')
  const writer = await context.newPage()
  await writer.goto('/')
  const otherCard = writer.locator('.question-card').filter({ hasText: 'Apa hal kecil yang belakangan ini bikin kamu merasa bahagia?' })
  await chooseEmoji(writer, otherCard.getByRole('group', { name: 'Reaksi pertanyaan', exact: true }), 'pizza', '🍕')
  await expect(conversationReactions.getByRole('button', { name: 'Reaksi 🍕, 1', exact: true })).toBeVisible()
  await expect(page.getByLabel('Jawaban anonim', { exact: true })).toHaveValue('Draft saat pertanyaan mendapat reaction')
  await conversationReactions.getByRole('button', { name: 'Reaksi 🐈, 1', exact: true }).click()
  await expect(otherCard.getByRole('button', { name: 'Reaksi 🐈, 1', exact: true })).toHaveCount(0)
  await writer.close()
  await page.reload()
  await expect(conversationReactions.getByRole('button', { name: 'Reaksi ☕, 1', exact: true })).toBeVisible()
  await expect(conversationReactions.getByRole('button', { name: 'Reaksi 🍕, 1', exact: true })).toBeVisible()
  await expect(conversationReactions.getByRole('button', { name: 'Reaksi 🐈, 1', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('emoji picker closes with Escape or an outside click, supports keyboard selection and preserves legacy reactions', async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/KTMXZ')
  const root = page.locator('[data-answer-id="demo-a1"]')
  const add = root.getByRole('button', { name: 'Tambah reaction', exact: true })
  await add.click()
  const dialog = page.getByRole('dialog', { name: 'Pilih reaction emoji' })
  await dialog.getByPlaceholder('Cari emoji').fill('cat')
  const bounds = await dialog.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(844)
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(add).toBeFocused()
  await add.click()
  await dialog.getByPlaceholder('Cari emoji').fill('coffee')
  await expect(dialog.getByRole('button', { name: '☕', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('Enter')
  await expect(dialog).toHaveCount(0)
  await expect(root.getByRole('button', { name: 'Reaksi ☕, 1', exact: true })).toBeVisible()
  await add.click()
  await dialog.getByPlaceholder('Cari emoji').fill('zzzzzz-no-emoji')
  await expect(dialog.getByText('Emoji tidak ditemukan', { exact: true })).toBeVisible()
  await page.getByRole('heading', { level: 1 }).click()
  await expect(dialog).toHaveCount(0)
  const writer = await context.newPage()
  await writer.goto('/KTMXZ')
  await page.getByLabel('Jawaban anonim', { exact: true }).fill('Draft saat reaction masuk dari tab lain')
  await chooseEmoji(writer, writer.locator('[data-answer-id="demo-a1"]'), 'pizza', '🍕')
  await expect(root.getByRole('button', { name: 'Reaksi 🍕, 1', exact: true })).toBeVisible()
  await expect(page.getByLabel('Jawaban anonim', { exact: true })).toHaveValue('Draft saat reaction masuk dari tab lain')
  await writer.close()
  await page.evaluate(() => {
    const saved = JSON.parse(localStorage.getItem('dheepask-demo-v1')!)
    saved.answerReactions['demo-a1'] = { counts: { heart: 3 }, mine: 'heart' }
    localStorage.setItem('dheepask-demo-v1', JSON.stringify(saved))
  })
  await page.reload()
  const heart = root.getByRole('button', { name: 'Reaksi ❤️, 3', exact: true })
  await expect(heart).toHaveAttribute('aria-pressed', 'true')
  await heart.click()
  await expect(root.getByRole('button', { name: 'Reaksi ❤️, 2', exact: true })).toHaveAttribute('aria-pressed', 'false')
})
